" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
filetype plugin indent on

" ================ General Config ====================
set backspace=indent,eol,start          "Allow backspace in insert mode
set history=1000                        "Store lots of :cmdline history
set visualbell                          "No sounds
set autoread                            "Reload files changed outside vim
set list listchars=tab:\ \ ,trail:·     "Display tabs and trailing spaces visually
set hidden                              "This makes vim act like all other editors, buffers can
syntax on                               "turn on syntax highlighting 
set mouse=a
set rnu nu
set splitbelow
" ================ Indentation ======================
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab
" ================ Scrolling ========================
set scrolloff=8                         "Start scrolling when we're 8 lines away from margins
set ignorecase                          "Ignore case when searching...
set smartcase                           " ...unless we type a capital
set incsearch
set nobackup
set nowritebackup
set cmdheight=2
set updatetime=300
set shortmess+=c
set signcolumn=yes
set updatetime=100
let mapleader=" "

if exists('+termguicolors')
  set termguicolors
endif

if filereadable(expand("~/.vim/settings/extensions.vim"))
  source ~/.vim/settings/extensions.vim
endif

" https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

so ~/.vim/settings/keymap.vim

autocmd InsertEnter,InsertLeave * set cul!

if has('persistent_undo')
  if !isdirectory(expand('~').'/.vim/backups')
    silent !mkdir ~/.vim/backups > /dev/null 2>&1
  endif
  set undodir=~/.vim/backups
  set undofile
endif

let g:lightline = {
      \ 'colorscheme': 'one',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'cocstatus', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'cocstatus': 'coc#status'
      \ },
      \ }

colorscheme palenight
